spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessActivity
      database: fitnessActivity
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

custom:
  rabbitmq:
    exchange:
      name: fitness.exchange
    routing:
      key: activity.tracking

server:
  port: 8082
