spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost/fitnessrecommondation
      database: fitnessrecommondation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
custom:
  rabbitmq:
    exchange:
      name: fitness.exchange
    routing:
      key: activity.tracking
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/