spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost/fitnessrecommondation
      database: fitnessrecommondation
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/