### POST request to example server
POST http://localhost:8082/api/activities
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "type": "RUNNING",
  "duration": 30,
  "distance": 5.0,
  "caloriesBurned": 300,
  "startTime": "2025-01-12T10:00:00Z",
  "additionalMetrics": {
    "distance": 5.2,
    "averageSpeed": 10.4,
    "maxHeartRate": 165
  }
}


###