### POST request to example server
POST http://localhost:8082/api/activities
Content-Type: application/json
Accept: application/json

{
  "userId": 2,
  "type": "SWIMMING",
  "duration": 10,
  "distance": 0.5,
  "caloriesBurned": 800,
  "startTime": "2025-02-12T10:00:00Z",
  "additionalMetrics": {
    "distance": 0.5,
    "averageSpeed": 10.4,
    "maxHeartRate": 165
  }
}


###
GET http://localhost:8082/api/activities
X-User-ID: 2

###
GET http://localhost:8082/api/activities/68124068a2cde208479a6108
