### POST request to example server
POST http://localhost:8082/api/activities
Content-Type: application/json
Accept: application/json

{
  "userId": "9fb67485-ae4c-4a46-a730-705c7ab21ae2",
  "type": "SWIMMING",
  "duration": 20,
  "distance": 0.8,
  "caloriesBurned": 1800,
  "startTime": "2025-03-12T10:00:00Z",
  "additionalMetrics": {
    "distance": 0.8,
    "averageSpeed": 5.3,
    "maxHeartRate": 170
  }
}


###
GET http://localhost:8082/api/activities
X-User-ID: 2

###
GET http://localhost:8082/api/activities/68124068a2cde208479a6108
