spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: Pratik39

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081